// Generated by Selenium IDE
package idebase.pkg;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoogleSearchTest1 {
	WebDriver driver;
 
  @Before
  public void setUp() {
    driver = new ChromeDriver();
  }
 
  @Test
  public void googleSearch() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(1050, 708));
    driver.findElement(By.id("APjFqb")).sendKeys("BOOKS");
    driver.findElement(By.name("btnK")).click();
    driver.close();
  }
  
//  @After
//  public void tearDown() {
//    driver.quit();
//  }
}
